# Generated by Django 4.2.2 on 2023-06-30 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['id']},
        ),
    ]
